#!/usr/bin/env bash
# ClipCatalyst Cloud — one-command bootstrap.
#
#   curl -fsSL https://raw.githubusercontent.com/allentackie-ops/clipcatalyst/main/api/bootstrap.sh | bash
#
# Brings up the API + worker + redis on a fresh box and prints the two things
# you need to wire the frontend: the public URL and the API token.
#
# Picks its own path, no flags required:
#   * GPU detected (nvidia-smi)      -> distil-large-v3 on cuda/float16
#   * no GPU                         -> base on cpu/int8 (works, just slower)
#   * working Docker daemon          -> docker compose stack
#   * no Docker (e.g. a RunPod pod)  -> native install + background processes
#
# Safe to re-run: it reuses an existing token and restarts the services.

set -euo pipefail

REPO_URL="${CC_REPO_URL:-https://github.com/allentackie-ops/clipcatalyst}"
BRANCH="${CC_BRANCH:-main}"
PORT="${CC_PORT:-8000}"

say()  { printf '\n\033[1;35m==>\033[0m \033[1m%s\033[0m\n' "$*"; }
info() { printf '    %s\n' "$*"; }
warn() { printf '\033[1;33m    !  %s\033[0m\n' "$*"; }
die()  { printf '\n\033[1;31mFAILED:\033[0m %s\n' "$*" >&2; exit 1; }

# --- 0. Locate (or fetch) the repo -----------------------------------------

if [ -f "docker-compose.yml" ] && [ -d "clipcatalyst_api" ]; then
  API_DIR="$(pwd)"
elif [ -f "api/docker-compose.yml" ]; then
  API_DIR="$(pwd)/api"
else
  say "Fetching ClipCatalyst"
  command -v git >/dev/null 2>&1 || {
    apt-get update -qq && apt-get install -y -qq git >/dev/null 2>&1 || die "git missing and auto-install failed"
  }
  WORK="${CC_WORKDIR:-$([ -d /workspace ] && echo /workspace || echo "$HOME")}"
  cd "$WORK"
  if [ -d clipcatalyst/.git ]; then
    info "Repo already present — pulling latest"
    git -C clipcatalyst fetch --quiet origin "$BRANCH" && git -C clipcatalyst checkout --quiet "$BRANCH" && git -C clipcatalyst pull --quiet origin "$BRANCH"
  else
    git clone --quiet --branch "$BRANCH" --depth 1 "$REPO_URL" clipcatalyst || die "clone failed"
  fi
  API_DIR="$WORK/clipcatalyst/api"
fi
cd "$API_DIR"
info "Working in $API_DIR"

# --- 1. Hardware -----------------------------------------------------------

say "Checking hardware"
if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1; then
  HAS_GPU=1
  GPU_NAME="$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1)"
  info "GPU: ${GPU_NAME:-detected}"
  WHISPER_MODEL="${CC_WHISPER_MODEL:-distil-large-v3}"
  WHISPER_DEVICE="cuda"
  WHISPER_COMPUTE="${CC_WHISPER_COMPUTE:-float16}"
else
  HAS_GPU=0
  warn "No GPU detected — falling back to CPU (jobs take minutes, not seconds)"
  WHISPER_MODEL="${CC_WHISPER_MODEL:-base}"
  WHISPER_DEVICE="cpu"
  WHISPER_COMPUTE="${CC_WHISPER_COMPUTE:-int8}"
fi
info "Whisper: $WHISPER_MODEL on $WHISPER_DEVICE ($WHISPER_COMPUTE)"

# --- 2. Config -------------------------------------------------------------

say "Writing configuration"
if [ -f .env ] && grep -q '^CC_API_TOKEN=.\+' .env; then
  API_TOKEN="$(grep '^CC_API_TOKEN=' .env | head -1 | cut -d= -f2-)"
  info "Reusing the existing API token in .env"
else
  if command -v openssl >/dev/null 2>&1; then
    API_TOKEN="$(openssl rand -hex 32)"
  else
    API_TOKEN="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  fi
  info "Generated a new API token"
fi

DATA_DIR="${CC_DATA_DIR:-$([ -d /workspace ] && echo /workspace/ccdata || echo "$API_DIR/ccdata")}"
mkdir -p "$DATA_DIR"

# Public origin: RunPod exposes pods at <POD_ID>-<PORT>.proxy.runpod.net over
# HTTPS, which is exactly what a browser on an HTTPS site needs.
PUBLIC_URL=""
if [ -n "${RUNPOD_POD_ID:-}" ]; then
  PUBLIC_URL="https://${RUNPOD_POD_ID}-${PORT}.proxy.runpod.net"
  info "RunPod detected — public URL: $PUBLIC_URL"
fi

cat > .env <<EOF
# Generated by bootstrap.sh — keep CC_API_TOKEN secret.
CC_API_TOKEN=$API_TOKEN
CC_WHISPER_MODEL=$WHISPER_MODEL
CC_WHISPER_DEVICE=$WHISPER_DEVICE
CC_WHISPER_COMPUTE=$WHISPER_COMPUTE
CC_DATA_DIR=$DATA_DIR
CC_JOB_TTL_HOURS=48
CC_PUBLIC_BASE_URL=$PUBLIC_URL
EOF
chmod 600 .env
info "Wrote $API_DIR/.env"

# --- 3. Bring the stack up -------------------------------------------------

if [ "${CC_DRY_RUN:-0}" = "1" ]; then
  say "Dry run — stopping before install"
  info "Config written; nothing installed and no services started."
  info "Token: $API_TOKEN"
  info "Data dir: $DATA_DIR"
  exit 0
fi

DOCKER_OK=0
if command -v docker >/dev/null 2>&1 && timeout 20 docker info >/dev/null 2>&1; then
  DOCKER_OK=1
fi

if [ "$DOCKER_OK" = "1" ]; then
  say "Starting with Docker Compose"
  COMPOSE=(docker compose -f docker-compose.yml)
  if [ "$HAS_GPU" = "1" ]; then
    if docker info 2>/dev/null | grep -qi nvidia; then
      COMPOSE+=(-f docker-compose.gpu.yml)
      info "nvidia runtime present — enabling GPU passthrough"
    else
      warn "GPU found but the nvidia container runtime isn't registered with Docker."
      warn "Install nvidia-container-toolkit, or re-run; continuing on CPU for now."
    fi
  fi
  "${COMPOSE[@]}" up -d --build || die "docker compose failed"
  RUN_MODE="docker"
else
  say "No Docker daemon — installing natively"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq >/dev/null 2>&1 || warn "apt-get update had warnings"
  apt-get install -y -qq ffmpeg redis-server fonts-dejavu-core >/dev/null 2>&1 \
    || die "could not install ffmpeg/redis (need root?)"
  info "Installed ffmpeg + redis"

  PY="$(command -v python3 || true)"
  [ -n "$PY" ] || die "python3 not found"
  "$PY" -m pip install --quiet --upgrade pip >/dev/null 2>&1 || true
  info "Installing Python dependencies (this takes a few minutes)…"
  "$PY" -m pip install --quiet -r requirements-worker.txt \
    || "$PY" -m pip install --quiet --break-system-packages -r requirements-worker.txt \
    || die "pip install failed"

  mkdir -p "$DATA_DIR/logs"
  redis-server --daemonize yes --appendonly yes --dir "$DATA_DIR" >/dev/null 2>&1 || true
  sleep 1

  # Stop previous run, if any.
  pkill -f 'uvicorn clipcatalyst_api.main:app' 2>/dev/null || true
  pkill -f 'celery -A clipcatalyst_api.queue_app' 2>/dev/null || true
  sleep 1

  set -a; . ./.env; set +a
  export CC_REDIS_URL="${CC_REDIS_URL:-redis://localhost:6379/0}"
  export PYTHONUNBUFFERED=1

  nohup "$PY" -m uvicorn clipcatalyst_api.main:app --host 0.0.0.0 --port "$PORT" \
    > "$DATA_DIR/logs/api.log" 2>&1 &
  nohup "$PY" -m celery -A clipcatalyst_api.queue_app worker --loglevel=info --concurrency=1 \
    > "$DATA_DIR/logs/worker.log" 2>&1 &
  info "API + worker started (logs in $DATA_DIR/logs/)"
  RUN_MODE="native"
fi

# --- 4. Wait for health ----------------------------------------------------

say "Waiting for the API to come up"
HEALTHY=0
for _ in $(seq 1 60); do
  if curl -fsS "http://localhost:${PORT}/v1/healthz" >/dev/null 2>&1; then
    HEALTHY=1
    break
  fi
  sleep 2
done

if [ "$HEALTHY" != "1" ]; then
  warn "API didn't answer on port $PORT within 2 minutes."
  if [ "$RUN_MODE" = "docker" ]; then
    warn "Check: docker compose logs --tail 50"
  else
    warn "Check: tail -50 $DATA_DIR/logs/api.log"
  fi
  die "startup health check failed"
fi

HEALTH_JSON="$(curl -fsS "http://localhost:${PORT}/v1/healthz" 2>/dev/null || echo '{}')"

# --- 5. Report -------------------------------------------------------------

printf '\n\033[1;32m========================================================\033[0m\n'
printf '\033[1;32m  ClipCatalyst Cloud is UP\033[0m\n'
printf '\033[1;32m========================================================\033[0m\n\n'
printf '  Mode      : %s (%s)\n' "$RUN_MODE" "$([ "$HAS_GPU" = 1 ] && echo GPU || echo CPU)"
printf '  Whisper   : %s / %s\n' "$WHISPER_MODEL" "$WHISPER_DEVICE"
printf '  Health    : %s\n' "$HEALTH_JSON"
printf '\n  \033[1mSEND THESE TWO LINES BACK:\033[0m\n\n'
if [ -n "$PUBLIC_URL" ]; then
  printf '  API_URL=%s\n' "$PUBLIC_URL"
else
  printf '  API_URL=https://<your-public-https-url-for-port-%s>\n' "$PORT"
  printf '\n'
  warn "No RunPod proxy URL detected — expose port $PORT over HTTPS."
  warn "A browser on an HTTPS site cannot call a plain http:// API."
fi
printf '  API_TOKEN=%s\n' "$API_TOKEN"
printf '\n  Keep the token private — it is the only thing standing between\n'
printf '  the open internet and your GPU bill.\n\n'
if [ "$HAS_GPU" = "1" ]; then
  printf '  First job also downloads the Whisper model (~1.5 GB) — allow a\n'
  printf '  few extra minutes for that one run only.\n\n'
fi
